# PHP as Linux Web App on Azure
# Build, package and deploy your PHP project to Azure Linux Web App.
# Add steps that run tests and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/php

pool:
  vmImage: 'windows-latest'
  
  steps:
  - task: CmdLine@2
  inputs:
    script: |
      echo Write your commands here
      
      echo Hello world

